# Generated by Django 2.1.7 on 2019-11-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artists',
        ),
    ]
