# Generated by Django 2.1.7 on 2019-11-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_moods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moods',
        ),
    ]
